const products = [
  {
    productID: 1,
    productName: "Samsung S21",
    description: "black in color",
    price: "₹ 25000",
    img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
    quantity: 0,
  },
  {
    productID: 2,
    productName: "Samsung M21",
    description: "white in color",
    price: "₹ 23000",
    img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
    quantity: 12,
  },
  {
    productID: 3,
    productName: "Redmi 9",
    description: "black in color",
    price: "₹ 35000",
    img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
    quantity: 18,
  },
  {
    productID: 4,
    productName: "Iphone 12",
    description: "Best mobile ever",
    price: "₹ 90500",
    img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
    quantity: 9,
  },
  {
    productID: 5,
    productName: "Samsung S21",
    description: "black in color",
    price: "₹ 25000",
    img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
    quantity: 5,
  },
  {
    productID: 6,
    productName: "Redmi 9",
    description: "black in color",
    price: "₹ 35000",
    img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
    quantity: 14,
  },
  {
    productID: 7,
    productName: "Samsung S21",
    description: "black in color",
    price: "₹ 25000",
    img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
    quantity: 11,
  },
  {
    productID: 8,
    productName: "Iphone 12",
    description: "Best mobile ever",
    price: "₹ 90500",
    img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
    quantity: 1,
  },
  {
    productID: 9,
    productName: "Samsung S21",
    description: "black in color",
    price: "₹ 25000",
    img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
    quantity: 1,
  },
];

export default products;
